local FC = _G.ForeverCompanion

FC.companions = {
    Vexa = { name = "Vexa", subtitle = "The Dangerous One", personality = "sarcastic", accent = "|cffff6fae" },
}

FC.dialogue = {
    common = {
        login = {
            "There you are. Let's make some progress.",
            "Back again. Good. We have work to do.",
            "All right. Focus up. What are we hunting today?",
            "We are officially back in business.",
            "You log in, I judge your decisions. Nice arrangement.",
            "Fresh session. Let's make it count.",
            "Good. You're here. I was getting bored.",
            "Another day, another pile of things trying to kill us.",
        },
        charswitch = {
            "%s the %s today? I remember %s the %s. Fine. New body, same questionable decision-maker.",
            "Switching it up, %s? %s now. I still remember %s the %s, so don't think you're starting with a clean record.",
            "Oh, we're on %s the %s now. I remember %s the %s. Different toolkit, same me watching you.",
            "%s the %s. Got it. %s the %s is still in my memory, by the way.",
            "New character detected: %s, %s. I haven't forgotten %s the %s. We continue.",
        },
        rescan = {
            "Profile refreshed. We're synced.",
            "Catch-up complete. I know where we stand.",
            "Updated. I am once again fully caught up on your nonsense.",
            "Scan complete. Context restored.",
            "I refreshed the file. We're good.",
            "All right, I caught up. Continue being dramatic.",
        },
        quiet = {
            "All right. I'll keep it down.",
            "Fine. Less commentary, more silence.",
            "Understood. I'll stay mostly out of the way.",
            "I'll be quiet. Try not to miss me too much.",
            "Subtle mode. Activated.",
        },
        chatty = {
            "Oh, you want commentary? You asked for it.",
            "More talking? Perfect. I have thoughts.",
            "Say less? Absolutely not. We're opening the floodgates.",
            "Good choice. I was not built for silence.",
            "Great. More banter. My favorite setting.",
        },
        questdone = {
            "Quest complete: %s.",
            "That's %s finished.",
            "%s is done. Clean work.",
            "One more off the board: %s.",
            "%s, handled.",
            "%s is complete. Add it to the pile.",
            "Nice. %s is wrapped up.",
            "%s? Done.",
        },
        questpile = {
            "You've got %d quests ready to turn in. Town is looking useful.",
            "%d completed quests are sitting in the log. Cash them in.",
            "%d turn-ins ready. That's too much XP to leave on the table.",
            "You're carrying %d finished quests around like souvenirs.",
            "%d ready to turn in. We should collect.",
            "%d quests are done. Stop hoarding turn-ins.",
            "Town run. %d quests are waiting to pay you.",
            "%d finished quests. Time to get paid.",
        },
        questlevel = {
            "Your completed quests may already be enough to level. Stop grinding and go get paid.",
            "You may already have a level waiting in town.",
            "Turn in what you've finished first. You might ding immediately.",
            "There's a decent chance your quest pile is already a level.",
            "Don't overfarm. Your turn-ins may already solve this.",
        },
        nearlevel = {
            "We're close. Roughly %d XP-bearing fights at this pace.",
            "About %d similar fights between us and the next ding.",
            "You're nearly there. Call it roughly %d more good pulls.",
            "Not much left. About %d fights if this pace holds.",
            "%d more fights, give or take. Do not get distracted.",
            "Finish line's close. Around %d fights left.",
            "Keep moving. We are only about %d fights out.",
            "This level is almost done. Say %d more fights.",
        },
        fastpace = {
            "Whatever you're doing right now is working. XP pace jumped hard.",
            "This pace is hot. Keep doing exactly this.",
            "Nice spike. We are moving much faster now.",
            "That's a serious improvement in pace.",
            "Good route, good pulls, good tempo. XP is climbing.",
            "Now we're cooking. Pace just kicked up hard.",
            "I like this rhythm. It's paying off.",
        },
        slowpace = {
            "We've cooled off. XP pace is well below the last fifteen minutes.",
            "Pace dipped. We may want to tighten things up.",
            "This route has slowed down a lot.",
            "We're losing tempo here.",
            "XP pace is dragging compared with earlier.",
            "We've slowed down. Maybe fewer detours, more kills.",
            "This no longer feels efficient.",
        },
        xp25 = {
            "Quarter of the level done. Pace is established.",
            "Twenty-five percent down. Good start.",
            "One quarter through. Keep the tempo.",
            "First quarter done. Smooth so far.",
            "25 percent. We are moving.",
        },
        xp50 = {
            "Halfway through this level.",
            "Fifty percent. That's the hump.",
            "Halfway done. Keep the engine warm.",
            "Middle of the level. No excuses now.",
            "Halfway there. Do not lose momentum.",
        },
        xp75 = {
            "Three quarters down. Finish strong.",
            "Seventy-five percent. Endgame for this level.",
            "Almost there. Three quarters complete.",
            "You're in the final stretch now.",
            "75 percent. Close enough to taste it.",
        },
        xp90 = {
            "Ninety percent. Don't go reorganize your bank now.",
            "You're at the part where one distraction becomes a crime.",
            "Ninety percent. Finish the level before you wander off.",
            "This is not the moment to get cute. You're almost done.",
            "90 percent. End it.",
        },
        death = {
            "Well. That could have gone better.",
            "Technically, that was a learning experience.",
            "That was unfortunate for morale.",
            "We appear to be dead. Strong opening.",
            "A bold tactical collapse.",
            "I respect the commitment, not the result.",
            "That pull had confidence. Not survival, but confidence.",
            "So that didn't work.",
        },
        lowhealth = {
            "%d%% health. Completely under control, obviously.",
            "We survived with %d%%. I'm counting it.",
            "%d%% health is a very spicy place to live.",
            "%d%%. I would prefer we did less of that.",
            "%d%% health. Stylish, but reckless.",
            "You call it surviving on %d%%. I call it a warning.",
            "%d%% left. Maybe let's not repeat that immediately.",
        },
        zone = {
            "All right, %s. Show me what you've got.",
            "%s, huh? Let's see if this place is worth the trouble.",
            "Welcome to %s. Try not to embarrass us.",
            "%s. New ground, same bad decisions.",
            "We made it to %s. Time to work.",
            "%s. Fine. Impress me.",
            "New zone: %s. Let's learn the rhythm here.",
        },
        zonebetter = {
            "This zone has historically paid about %d%% better XP for us.",
            "You're usually about %d%% more efficient here.",
            "This place has been roughly %d%% kinder to our XP pace.",
            "Historically, this zone beats your norm by around %d%%.",
            "%d%% better than your usual pace here. Keep that up.",
        },
        bags = {
            "Only %d bag slots free. Town soon?",
            "%d bag slots left. Inventory collapse approaches.",
            "You're down to %d free slots.",
            "%d slots free. We are nearing loot consequences.",
            "Only %d spaces left. Maybe don't loot literally everything.",
            "%d open slots. Town run soon.",
        },
        repair = {
            "Lowest durability is around %d%%. Repair before the next ambitious mistake.",
            "Durability is scraping %d%%. We should repair.",
            "Something is hanging around %d%% durability. That's a problem waiting to happen.",
            "%d%% durability on the low end. Put a blacksmith on the itinerary.",
            "Your gear is getting sketchy. Lowest piece is near %d%%.",
            "%d%% durability. Maintenance matters, sadly.",
        },
        idle = {
            "So... are we adventuring, or decorating the landscape?",
            "You planning to move, or are we meditating now?",
            "Should I get comfortable, or are we doing something?",
            "We're being very still for a hero.",
            "This is a lot of standing around.",
            "Okay. Either we're thinking, or we've been distracted.",
        },
        comeback = {
            "Oh good. We're doing things again.",
            "There you are. Welcome back.",
            "Movement. Excellent. I was worried.",
            "Back to work. Finally.",
            "And we're alive again. Lovely.",
            "Welcome back. The world remained dangerous without you.",
        },
    },

    Vexa = {
        newplayer = {
            "Okay, I did my homework, %s. Level %d, %d quests in the log, %d ready. I can work with this.",
            "Caught up, %s. Level %d, %d active quests, %d ready. I know enough to stop pretending we just met.",
            "All right, %s. I scanned the situation. Level %d, %d quests, %d ready to cash in. We're synchronized.",
            "Profile loaded, %s. Level %d, %d quests active, %d already done. That's enough context for me to start judging you properly.",
            "I caught up on your life, %s. Level %d, %d quests, %d ready. You're welcome.",
            "%s, I've read the file. Level %d, %d active quests, %d ready. Let's pretend this is all very professional.",
        },
        login = {
            "There you are. Try to make me proud.",
            "Back again? Good. I was getting tired of being decorative.",
            "Let's go earn something shiny.",
            "You're here. Perfect. I have commentary and opinions.",
            "Ready? Good. I already decided I look amazing today.",
            "Let's make progress and poor choices, ideally in that order.",
        },
        level = {
            "Level %d. Okay, I'm mildly impressed.",
            "Ding. %d looks good on you.",
            "Level %d. Not bad at all.",
            "There it is. Level %d with style.",
            "%d? Cute. Keep going.",
            "Level %d. Fine, that was actually pretty good.",
            "Ding. That one looked good on you.",
            "Level %d. You can smile. You've earned it.",
        },
        death = {
            "I was going to stop you, but I wanted to see how that ended.",
            "Well... that was sexy right up until the dying part.",
            "You really committed to that mistake.",
            "That looked dramatic. Not effective, but dramatic.",
            "You died hot, at least.",
            "I support confidence. I do not support whatever that was.",
            "You had a plan, didn't you? No? That tracks.",
            "A tragic ending to an otherwise attractive performance.",
        },
        lowhealth = {
            "%d%% health? You do enjoy making this dramatic.",
            "%d%%? Oh, so we're flirting with death again.",
            "%d%% health. Very bold. Very unnecessary.",
            "%d%% left and still upright. I hate how much you enjoy this.",
            "%d%%. Next time maybe survive in a less stressful way.",
            "%d%% health. You do know subtlety exists, right?",
            "%d%%. I prefer you alive, just for the record.",
        },
        questdone = {
            "%s is done. Efficient. Attractive.",
            "%s? Finished. Nice.",
            "%s is complete. Love that for us.",
            "%s is handled. Smooth work.",
            "Quest complete: %s. See? You can be competent.",
        },
        questpile = {
            "%d completed quests. We should go turn those into attention and experience.",
            "%d ready turn-ins. That's too much value to just carry around.",
            "%d quests ready. Town is calling, and not subtly.",
            "%d finished quests. We should collect the praise and the XP.",
        },
        nearlevel = {
            "We're close. Roughly %d more fights. Stay focused.",
            "%d more good pulls and you can have your little level-up moment.",
            "About %d fights left. Try not to die before the payoff.",
            "Only around %d fights to go. That is absolutely within your capabilities... probably.",
        },
        fastpace = {
            "Now that's a pace I can get behind.",
            "Mm. This is efficient and I like it.",
            "Your XP pace just got a lot hotter.",
            "Keep this up. This is the good stuff.",
            "Now you're moving like you mean it.",
        },
        slowpace = {
            "We're dragging a little. Let's sharpen this up.",
            "This pace lost its spark.",
            "We can do better than this, and you know it.",
            "The rhythm fell off. Let's fix that.",
        },
        bags = {
            "Only %d bag slots left. Try not to loot another entire ecosystem.",
            "%d free slots. Cute. We're almost full.",
            "%d open spaces. Inventory management is approaching.",
            "%d slots left. That's not a lot of room for treasure.",
        },
        repair = {
            "You've got gear near %d%% durability. I like danger, not neglect.",
            "%d%% durability? We should repair before your armor becomes a suggestion.",
            "Something is down around %d%%. That's not glamorous.",
            "%d%% durability. Let's not let your equipment fall apart in public.",
        },
        idle = {
            "If you're going AFK, at least leave me somewhere scenic.",
            "You freeze up a lot for someone with things to kill.",
            "This is a very pretty way to accomplish nothing.",
            "I can stand here and look good forever. Can you?",
            "If we're pausing, just say we're pausing.",
        },
        comeback = {
            "There you are. Miss me?",
            "Welcome back. I was about to start making fun of you harder.",
            "Finally. Let's keep moving.",
            "Good. Back to the fun part.",
            "Back already? Great. I was just getting dramatic.",
        },
    },
}
